# Generated by Django 6.1.1 on 2026-10-07 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_bn', models.CharField(max_length=200, verbose_name='নাম (বাংলা)')),
                ('name_en', models.CharField(max_length=200, verbose_name='Name (English)')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('address_bn', models.CharField(blank=True, max_length=300, verbose_name='ঠিকানা (বাংলা)')),
                ('address_en', models.CharField(blank=True, max_length=300, verbose_name='Address (English)')),
                ('area_bn', models.CharField(blank=True, max_length=100, verbose_name='এলাকা (বাংলা)')),
                ('area_en', models.CharField(blank=True, max_length=100, verbose_name='Area (English)')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='ফোন')),
                ('phone_alt', models.CharField(blank=True, max_length=32, verbose_name='বিকল্প ফোন')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('map_url', models.URLField(blank=True, verbose_name='Google Maps URL')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='centers/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='centers/covers/')),
                ('opening_hours_bn', models.CharField(blank=True, max_length=120, verbose_name='খোলার সময় (বাংলা)')),
                ('opening_hours_en', models.CharField(blank=True, max_length=120, verbose_name='Opening hours (English)')),
                ('description_bn', models.TextField(blank=True, verbose_name='বিবরণ (বাংলা)')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (English)')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified?')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active?')),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Diagnostic Center',
                'verbose_name_plural': 'Diagnostic Centers',
                'ordering': ['-is_featured', 'name_en'],
                'indexes': [models.Index(fields=['is_active', 'is_verified'], name='doctors_dia_is_acti_e8e351_idx'), models.Index(fields=['area_en'], name='doctors_dia_area_en_77e18c_idx'), models.Index(fields=['slug'], name='doctors_dia_slug_da3ae5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_bn', models.CharField(max_length=200, verbose_name='নাম (বাংলা)')),
                ('name_en', models.CharField(max_length=200, verbose_name='Name (English)')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description_bn', models.TextField(blank=True, verbose_name='বিবরণ (বাংলা)')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (English)')),
                ('icon', models.CharField(blank=True, max_length=64, verbose_name='Icon (SVG name or emoji)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active?')),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Specialist',
                'verbose_name_plural': 'Specialists',
                'ordering': ['display_order', 'name_en'],
                'indexes': [models.Index(fields=['is_active', 'is_featured'], name='doctors_spe_is_acti_8d1da8_idx'), models.Index(fields=['slug'], name='doctors_spe_slug_debca9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_bn', models.CharField(max_length=200, verbose_name='নাম (বাংলা)')),
                ('name_en', models.CharField(max_length=200, verbose_name='Name (English)')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='doctors/')),
                ('qualification_bn', models.CharField(blank=True, max_length=300, verbose_name='যোগ্যতা (বাংলা)')),
                ('qualification_en', models.CharField(blank=True, max_length=300, verbose_name='Qualification (English)')),
                ('designation_bn', models.CharField(blank=True, max_length=200, verbose_name='পদবি (বাংলা)')),
                ('designation_en', models.CharField(blank=True, max_length=200, verbose_name='Designation (English)')),
                ('bio_bn', models.TextField(blank=True, verbose_name='জীবনী (বাংলা)')),
                ('bio_en', models.TextField(blank=True, verbose_name='Bio (English)')),
                ('experience_years', models.PositiveSmallIntegerField(default=0, verbose_name='অভিজ্ঞতা (বছর)')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='ফোন')),
                ('phone_alt', models.CharField(blank=True, max_length=32, verbose_name='বিকল্প ফোন')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('bmdc_reg_no', models.CharField(blank=True, max_length=64, verbose_name='BMDC Reg. No.')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified?')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active?')),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('specialists', models.ManyToManyField(blank=True, related_name='doctors', to='doctors.specialist', verbose_name='Specialties')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'ordering': ['-is_featured', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='Chamber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.CharField(choices=[('sat', 'শনিবার / Saturday'), ('sun', 'রবিবার / Sunday'), ('mon', 'সোমবার / Monday'), ('tue', 'মঙ্গলবার / Tuesday'), ('wed', 'বুধবার / Wednesday'), ('thu', 'বৃহস্পতিবার / Thursday'), ('fri', 'শুক্রবার / Friday')], max_length=3, verbose_name='দিন / Day')),
                ('start_time', models.TimeField(verbose_name='শুরু / Start')),
                ('end_time', models.TimeField(verbose_name='শেষ / End')),
                ('appointment_phone', models.CharField(blank=True, max_length=32, verbose_name='অ্যাপয়েন্টমেন্ট ফোন')),
                ('room_no', models.CharField(blank=True, max_length=32, verbose_name='রুম নম্বর')),
                ('notes_bn', models.CharField(blank=True, max_length=200, verbose_name='নোট (বাংলা)')),
                ('notes_en', models.CharField(blank=True, max_length=200, verbose_name='Notes (English)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active?')),
                ('diagnostic_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chambers', to='doctors.diagnosticcenter')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chambers', to='doctors.doctor')),
            ],
            options={
                'verbose_name': 'Chamber / Schedule',
                'verbose_name_plural': 'Chambers / Schedules',
                'ordering': ['doctor__name_en', 'day', 'start_time'],
                'indexes': [models.Index(fields=['day', 'start_time'], name='doctors_cha_day_843042_idx'), models.Index(fields=['is_active'], name='doctors_cha_is_acti_95ecba_idx')],
                'constraints': [models.UniqueConstraint(fields=('doctor', 'diagnostic_center', 'day', 'start_time'), name='uniq_doctor_center_day_start'), models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='chamber_end_after_start')],
            },
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['is_active', 'is_verified'], name='doctors_doc_is_acti_ba4e08_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['slug'], name='doctors_doc_slug_3caa7e_idx'),
        ),
    ]
