# Generated by Django 6.1.1 on 2026-10-08 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bn', models.CharField(max_length=100, verbose_name='জেলা (বাংলা)')),
                ('name_en', models.CharField(max_length=100, verbose_name='District (English)')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('division_bn', models.CharField(blank=True, max_length=100, verbose_name='বিভাগ (বাংলা)')),
                ('division_en', models.CharField(blank=True, max_length=100, verbose_name='Division (English)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active?')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'ordering': ['display_order', 'name_en'],
                'indexes': [models.Index(fields=['slug'], name='doctors_dis_slug_83d925_idx'), models.Index(fields=['is_active'], name='doctors_dis_is_acti_0beb9e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Upazila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bn', models.CharField(max_length=100, verbose_name='উপজেলা (বাংলা)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Upazila (English)')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active?')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upazilas', to='doctors.district')),
            ],
            options={
                'verbose_name': 'Upazila',
                'verbose_name_plural': 'Upazilas',
                'ordering': ['district__display_order', 'display_order', 'name_en'],
            },
        ),
        migrations.AddField(
            model_name='diagnosticcenter',
            name='upazila',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centers', to='doctors.upazila', verbose_name='উপজেলা / Upazila'),
        ),
        migrations.AddIndex(
            model_name='diagnosticcenter',
            index=models.Index(fields=['upazila', 'is_active'], name='doctors_dia_upazila_1cb8ca_idx'),
        ),
        migrations.AddIndex(
            model_name='upazila',
            index=models.Index(fields=['slug'], name='doctors_upa_slug_66ac1b_idx'),
        ),
        migrations.AddIndex(
            model_name='upazila',
            index=models.Index(fields=['is_active'], name='doctors_upa_is_acti_41f5c3_idx'),
        ),
        migrations.AddIndex(
            model_name='upazila',
            index=models.Index(fields=['district', 'is_active'], name='doctors_upa_distric_4ff5fc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='upazila',
            unique_together={('district', 'name_en')},
        ),
    ]
